services:
  postgres:
    image: postgres:16
    env_file:
      - .env.development
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: DB_USERNAME
      POSTGRES_PASSWORD: DB_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env.development
    environment:
      DB_HOST: postgres
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  postgres_data:
